In [1]:
import pandas as pd

In [2]:
data=pd.read_html('https://results.eci.gov.in/ResultAcGenMar2022/ConstituencywiseS241.htm?ac=1')

In [3]:
len(data)

10

In [4]:
type(data)

list

In [5]:
result=data[9]

In [6]:
type(result)

pandas.core.frame.DataFrame

In [7]:
result

,0,1,2,3,4,5,6,7,8
0,Uttar Pradesh-Behat,Uttar Pradesh-Behat,Uttar Pradesh-Behat,Uttar Pradesh-Behat,Uttar Pradesh-Behat,Uttar Pradesh-Behat,Uttar Pradesh-Behat,Uttar Pradesh-Behat,Uttar Pradesh-Behat
1,Result Status,Result Status,Result Status,Result Status,Result Status,Result Status,Result Status,Result Status,Result Status
2,O.S.N.,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes,NaN,NaN
3,1,Umar Ali Khan,Samajwadi Party,134396,117,134513,47.81,NaN,NaN
4,2,Naresh Saini,Bharatiya Janata Party,96389,244,96633,34.34,NaN,NaN
5,3,Poonam Kamboj,Indian National Congress,1626,6,1632,0.58,NaN,NaN
6,4,Rais Malik,Bahujan Samaj Party,45010,65,45075,16.02,NaN,NaN
7,5,Sushil Kumar,Aam Aadmi Party,1161,1,1162,0.41,NaN,NaN
8,6,Ali Khan,Independent,409,0,409,0.15,NaN,NaN
9,7,Mo. IKram,Independent,271,1,272,0.1,NaN,NaN
10,8,Dharampal Singh,Independent,560,0,560,0.2,NaN,NaN
11,9,NOTA,None of the Above,1116,1,1117,0.4,NaN,NaN
12,NaN,Total,NaN,280938,435,281373,NaN,NaN,NaN

In [8]:
result=result.drop(result.columns[[0,1,2]], axis=0)

In [9]:
result=result.drop(result.columns[[7, 8]], axis=1)

In [10]:
result

      0                1                         2       3    4       5      6
3     1    Umar Ali Khan           Samajwadi Party  134396  117  134513  47.81
4     2     Naresh Saini    Bharatiya Janata Party   96389  244   96633  34.34
5     3    Poonam Kamboj  Indian National Congress    1626    6    1632   0.58
6     4       Rais Malik       Bahujan Samaj Party   45010   65   45075  16.02
7     5     Sushil Kumar           Aam Aadmi Party    1161    1    1162   0.41
8     6         Ali Khan               Independent     409    0     409   0.15
9     7        Mo. IKram               Independent     271    1     272    0.1
10    8  Dharampal Singh               Independent     560    0     560    0.2
11    9             NOTA         None of the Above    1116    1    1117    0.4
12  NaN            Total                       NaN  280938  435  281373    NaN

In [11]:
result.drop([12], axis=0, inplace=True)

In [12]:
result

    0                1                         2       3    4       5      6
3   1    Umar Ali Khan           Samajwadi Party  134396  117  134513  47.81
4   2     Naresh Saini    Bharatiya Janata Party   96389  244   96633  34.34
5   3    Poonam Kamboj  Indian National Congress    1626    6    1632   0.58
6   4       Rais Malik       Bahujan Samaj Party   45010   65   45075  16.02
7   5     Sushil Kumar           Aam Aadmi Party    1161    1    1162   0.41
8   6         Ali Khan               Independent     409    0     409   0.15
9   7        Mo. IKram               Independent     271    1     272    0.1
10  8  Dharampal Singh               Independent     560    0     560    0.2
11  9             NOTA         None of the Above    1116    1    1117    0.4

In [13]:
 result.to_csv('Behat.csv', index=False,header=None)